Optimize price script.
EdgeApp/edge-notifications pull request #5
Opened 2020-09-16 23:07 UTC by passabilities

2020-09-30 19:58 UTC, passabilities commented on src/NotificationManager.ts
> +      console.log('Messages sent:', response)
remove

2020-09-30 19:58 UTC, passabilities commented on src/index.ts
> +  }
Promise.all

2020-09-30 19:58 UTC, passabilities commented on src/index.ts
> +          await sendNotification(priceMap[currencyCode][hours], deviceTokens)
Promise.all

2020-09-30 19:58 UTC, passabilities commented on src/index.ts
> +function sleep(ms = 1000) {
add constant var

2020-09-30 19:58 UTC, passabilities commented on src/ratesServer.ts
> +    const { data } = await axios(`${this.uri}/v${this.version}/${path}`, { timeout: 10000 })
constant var

2020-09-30 19:58 UTC, passabilities commented on src/models/base.ts
> +      const item = await this.fetch(id)
bulk fetch with `{ keys: ids }`

2020-09-30 19:58 UTC, passabilities commented on src/models/base.ts
> +        skip: page * pageSize,
remove

2020-09-30 19:58 UTC, passabilities commented on src/price-script/checkPriceChanges.ts
> +    console.log('=================')
remove

2020-09-30 19:58 UTC, passabilities commented on src/price-script/checkPriceChanges.ts
> +      while(true) {
use while(done)

2020-09-30 19:58 UTC, passabilities commented on src/price-script/checkPriceChanges.ts
> +  while (true) {
use the if logic below

2020-09-30 19:58 UTC, passabilities commented on src/price-script/fetchThresholdPrices.ts
> +function sleep(ms = 1000) {
move to constant

2020-09-30 19:58 UTC, passabilities commented on src/price-script/fetchThresholdPrices.ts
> +    else if (hoursAgo > threshold.lastUpdated)
combine

2020-09-30 19:58 UTC, passabilities commented on src/price-script/fetchThresholdPrices.ts
> +      priceData.price = displayPrice
move to function and unit test

2020-09-30 19:58 UTC, thehobbit85 requested changes
The ones that Noah added

2020-10-01 00:40 UTC, thehobbit85 approved these changes

2020-10-01 00:40 UTC, merged